title: <p align="center"> Prathmesh Rahate </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="************">LinkedIn</a> |
  <a href="https://github.com/prathmeshvr">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  <br>
  </p>



theme: jekyll-theme-minimal
